services:
  service_jekyll:
    build:
      dockerfile: Dockerfile
      context: .
    platform: linux/amd64
    container_name: local_jekyll
    tty: true
    stdin_open: true
    volumes:
      - ./my-blog:/code
    command: bundle exec jekyll serve --host 0.0.0.0
    ports:
      - "4000:4000"
