services:
  service_jekyll:
    image: local/jekyll:latest
    build:
      dockerfile: Dockerfile
      context: .
    platform: linux/amd64
    container_name: local_jekyll
    tty: true
    stdin_open: true
    volumes:
      - ./my-blog:/code
    command: bundle exec jekyll serve --livereload --host 0.0.0.0
    ports:
      - "127.0.0.1:4000:4000"
      - "127.0.0.1:35729:35729"
