version: "3"
services:
  service_jekyll:
    image: jekyll/jekyll:4
    platform: linux/amd64
    container_name: local_jekyll
    tty: true
    stdin_open: true
    volumes:
      - ./my-blog:/srv/jekyll
    command: jekyll serve 
    ports:
      - "4000:4000"
