title: Shun Kiyono
author:
  name: Shun Kiyono
  twitter: shunkiyono
  url: https://butsugiri.github.io
email: ""
description: NLP researcher and engineer
baseurl: ""
url: "https://butsugiri.github.io"
lang: en
favicon: /assets/favicon.svg
twitter:
  username: shunkiyono
github_username: butsugiri

theme: no-style-please
theme_config:
  show_description: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

scholar:
  repository: /repository
  bibliography_template: bibtemplate
  style: association-for-computational-linguistics
